version: '3.0'
services:
 nginx_cont:
   image: nginx
   ports:
    - "80:80"
   volumes:
    - /home/ec2-user/dir:/abc
    
 mysql_cont:
   image: mysql
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=secretpass
   volumes:
    - /home/ec2-user/sql:/database
